# display_name & nick_name can only contain Alphanumerics & dashes
users:
  - user_principal_name: "<sample user email>"
    display_name: "<display name>"
    nick_name: "<short handed name>"
    roles:
      - name: "<Role name>" # Applicable only for azure built in roles. Check the available built in roles against the resource
        scope: "<Resource Id>"
      - name: "<Role name2>"
        scope: "<Resource Id>"    
  - user_principal_name: "<sample user email>"
    display_name: "<display name>"
    nick_name: "<short handed name>"
    roles:
      - name: "<Role name>"
        scope: "<Resource Id>"    
client_tenant:
  client_name: "<moderator_client_name>" # Client storage account name
  client_id: "<moderator_client_id>"
  client_secret: "<moderator_client_secret>"
  subscription_id: "<moderator_subscription_id>"
  tenant_id: "<moderator_tenant_id>"
key_vault_id: "<key_vault_id>"

